---
#VPN configuration

#http://www.elastichosts.com/support/tutorials/linux-l2tpipsec-vpn-client/

#l2tp/ipsec install

  - name: install openswan (for l2tp/ipsec vpn)
    apt: name=openswan state=latest update_cache=yes

  - name: install xl2tpd (for l2tp/ipsec vpn)
    apt: name=xl2tpd state=latest update_cache=yes


#[copy a bunch of templates here]



#start vpn

  - name: start openswan
    service: name=openswan state=start

  - name: start xl2tpd
    service: name=xl2tpd state=start

  - name: start ipsec connection
    command: ipsec auto --up L2TP-PSK

  - name: start the tunnel via xl2tpd
    command: echo "c vpn-connection" > /var/run/xl2tpd/l2tp-control

  - name: add the ip route for the vpn
    command: ip route add <vpn subnet/cider> via <vpn gateway>



#route all internet traffic over the vpn




#openvpn config

#  - name: install openvpn (for vpn)
#    apt: name=openvpn state=latest update_cache=yes
